using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using Mono.CSharp;
using UnityExplorerForLobotomyCorporation.UnityExplorer.Config;

// Thanks to ManlyMarco for this

namespace UnityExplorerForLobotomyCorporation.UnityExplorer.CSConsole
{
    public class ScriptEvaluator : Evaluator, IDisposable
    {
        internal static StreamReportPrinter _reportPrinter;

        private static readonly HashSet<string> StdLib = new HashSet<string>(StringComparer.InvariantCultureIgnoreCase)
        {
            "mscorlib",
            "System.Core",
            "System",
            "System.Xml",
        };

        internal TextWriter _textWriter;

        public ScriptEvaluator(TextWriter tw) : base(BuildContext(tw))
        {
            _textWriter = tw;

            ImportAppdomainAssemblies();
            AppDomain.CurrentDomain.AssemblyLoad += OnAssemblyLoad;
        }

        public void Dispose()
        {
            AppDomain.CurrentDomain.AssemblyLoad -= OnAssemblyLoad;
            _textWriter.Dispose();
        }

        private void OnAssemblyLoad(object sender,
            AssemblyLoadEventArgs args)
        {
            var name = args.LoadedAssembly.GetName().Name;

            if (StdLib.Contains(name))
            {
                return;
            }

            Reference(args.LoadedAssembly);
        }

        private void Reference(Assembly asm)
        {
            var name = asm.GetName().Name;

            if (name == "completions") // ignore assemblies generated by mcs' autocomplete.
            {
                return;
            }

            foreach (var blacklisted in ConfigManager.CSConsole_Assembly_Blacklist.Value.Split(';'))
            {
                var bl = blacklisted;
                if (bl.EndsWith(".dll", StringComparison.OrdinalIgnoreCase))
                {
                    bl = blacklisted.Substring(0, bl.Length - 4);
                }

                if (string.Equals(bl, name, StringComparison.OrdinalIgnoreCase))
                {
                    return;
                }
            }

            ReferenceAssembly(asm);
        }

        private static CompilerContext BuildContext(TextWriter tw)
        {
            _reportPrinter = new StreamReportPrinter(tw);

            var settings = new CompilerSettings
            {
                Version = LanguageVersion.Experimental,
                GenerateDebugInfo = false,
                StdLib = true,
                Target = Target.Library,
                WarningLevel = 0,
                EnhancedWarnings = false,
            };

            return new CompilerContext(settings, _reportPrinter);
        }

        private void ImportAppdomainAssemblies()
        {
            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                var name = assembly.GetName().Name;
                if (StdLib.Contains(name))
                {
                    continue;
                }

                try
                {
                    Reference(assembly);
                }
                catch // (Exception ex)
                {
                    //ExplorerCore.LogWarning($"Excepting referencing '{name}': {ex.GetType()}.{ex.Message}");
                }
            }
        }
    }
}
